### ISSUE TITLE
build fail with bazel version 0.28.1

### ISSUE THREAD

**Issue by Lingchao1** [google/private-join-and-compute#10]
build error with command：
bazel build :all --incompatible_disable_deprecated_attr_params=false --incompatible_depset_is_not_iterable=false --incompatible_new_actions_api=false --incompatible_no_support_tools_in_action_inputs=false

the error msg is :

ERROR: C:/users/lll/_bazel_lll/ct3wwz7r/external/com_github_gflags_gflags/BUILD:16:16: Executing genrule @com_github_gflags_gflags//:gflags_google_h failed (Exit -1). Note: Remote connection/protocol failed with: execution failed
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(184): CreateProcessW("c:\tools\msys64\usr\bin\bash.exe" -c "source external/bazel_tools/tools/genrule/genrule-setup.sh; awk '{ gsub(/@ns@/, \"google\"); gsub(/@NS@/, \"GOOGLE\"); print; }' external/com_github_gflags_(...)): 绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆?

**Comment by karnseth** [comment]
Hey Ling,

I think the issue is similar to https://github.com/bazelbuild/bazel/issues/6053. It may work now that we have updated to allow compiling with the most recent version of Bazel. Could you try again with Bazel 3.0.0+?

**Comment by TH-1016** [comment]
Hey, i have the similar problem as you. Could you please give me some suggestions? Thank you!

**Comment by shehramjamil** [comment]
I have the same error but with the slight change 
**CreateProcessW("C:\Program Files (x86)\Java\jre1.8.0_261\bash.exe

The complete error is as follows.

C:/users/sjamil/_bazel_sjamil/wzpzhqus/external/com_github_gflags_gflags/BUILD:16:30: Executing genrule @com_github_gflags_gflags//:gflags_google_h failed (Exit -1). Note: Remote connection/protocol failed with: execution failed
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): **CreateProcessW("C:\Program Files (x86)\Java\jre1.8.0_261\bash.exe"** -c "source external/bazel_tools/tools/genrule/genrule-setup.sh; awk '{ gsub(/@ns@/, \"google\"); gsub(/@NS@/, \"GOOGLE\"); print; }' external/com_github_gflags_gflags/src/gflags_ns.h.in > bazel-out/host/bin/external/com_github_gflags_gflags/gflags_google.h"): The system cannot find the file specified.
 (error: 2)

Please help

**Comment by karnseth** [comment]
Hey @TH-1016 , @shehramjamil, the issue seems to be with running gflags on windows. https://github.com/google/private-join-and-compute/pull/20 addressed some of these issues. Could you try again?
