### ISSUE TITLE
Use absl::Status instead of custom fork

### ISSUE THREAD

**Issue by SanjayVas** [google/private-join-and-compute#15]
Status has been released into the open-source [Abseil](https://github.com/abseil/abseil-cpp) library, which this project already depends on.

Note that Abseil does not have StatusOr currently. There is a Google-released version in [protocolbuffers](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/stubs/statusor.h), which this project also already depends on.

**Comment by karnseth** [comment]
Hi Sanjay,

Abseil will be releasing StatusOr, we will change our code over when that happens.

**Comment by efoxepstein** [comment]
absl::StatusOr is [now available](https://abseil.io/blog/2020-091021-status).

**Comment by karnseth** [comment]
Fixed in Commit # aa2d68e68193547e88a120c667e173662abd7478
