### ISSUE TITLE
Unable to view dummy data in tmp folder

### ISSUE THREAD

**Issue by Rapharel** [google/private-join-and-compute#18]
Hi, have been following README instructions, but unable to view the data for the server and client at the specified locations /tmp/dummy_server_data.csv and /tmp/dummy_client_data.csv. 

Not sure what I've been doing wrong as no error messages. Your help is much appreciated as I'd like to extend this great work to my own set of data. 

bazel 3.5.0-homebrew, macOS 10.14.6

Thank you

**Comment by karnseth** [comment]
Hey Rapharel, could you explain what the issue is in a bit more detail? Are the files not generated at those locations? Or do you get an error when trying to open them?

**Comment by Rapharel** [comment]
H @karnseth , thank you for getting back. It was an error on my part, having thought that /tmp/dummy_server_data.csv was stored in the project directory, when in fact it is in the users root directory. 
Thanks to you and the team for creating this great project.
