### ISSUE TITLE
Homomorphic encryption can “understand” the encrypted’s data? 

### ISSUE THREAD

**Issue by imvieira** [google/private-join-and-compute#3]
First of all congratulations for PIS project! 

This is a question I have. I am not expert in this subject, so please, be kind on the answer.

I understood the Homomorphic encryption is public key encryption that allows someone to operate on encrypted data without accessing the data. 

Let's suppose the word "CASA" is cryptographed, and a homomorphic encryption is done on that encrypted word.

My question is:

Homomorphic will understand the "meaning" of encrypted text? Homomorphic will know that the encrypted word is also "CASA" ? 

Thank you.

**Comment by aarshkshah1992** [comment]
@imvieira  No, the receiver of the encrypted text will have no idea what the actual text is. He/she can only perform some computation on it to get an 'encrypted result' which can then be decrypted by the sender.
