### ISSUE TITLE
run "bazel build :all"  failed 

### ISSUE THREAD

**Issue by yuanyinxiaing** [google/private-join-and-compute#8]

**Comment by yuanyinxiaing** [comment]
1、My question：
cannot build the project success，want to know how to solve this problem：
2、i try to build the project like following：
bazel build :all --incompatible_disable_deprecated_attr_params=false --incompatible_depset_is_not_iterable=false --incompatible_new_actions_api=false --incompatible_no_support_tools_in_action_inputs=false

3、i get the error like following：
ERROR: /Users/yyx/IdeaProjects/demorun/private-join-and-compute/BUILD:17:1: in srcs attribute of _generate_cc rule //:_match_proto_grpc_codegen: '//:_match_proto_only' does not have mandatory providers: 'proto'. Since this rule was created by the macro 'grpc_proto_library', the error might have been caused by the macro implementation
ERROR: Analysis of target '//:match_proto' failed; build aborted: Analysis of target '//:_match_proto_grpc_codegen' failed; build aborted

**Comment by rbrowngt** [comment]
Having the same problem, any update?

**Comment by karnseth** [comment]
Hello,
We suspect this issue is due to the recent Bazel update. We are working on a fix, but you should be able to compile with Bazel 0.28.1.

**Comment by karnseth** [comment]
This should work on the latest version of Bazel, after commit 391f0934e537e4399365865f1421c6b8f757b966
