### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by jklein9d** [google/private-join-and-compute#9]
I've tried to build using both methods in the README.

This is on mac osx High Sierra 10.13.3 running the latest version of bazel (1.1.0)

bazel build :all
and I received a bunch of errors.

I also tried the alternate build method and it also failed:
bazel build :all --incompatible_disable_deprecated_attr_params=false --incompatible_depset_is_not_iterable=false --incompatible_new_actions_api=false --incompatible_no_support_tools_in_action_inputs=false
INFO: Writing tracer profile to '/private/var/tmp/_bazel_jklein/94f892001698c23c1f7f07922b0f7cea/command.profile.gz'
ERROR: /Users/jklein/Sites/htdocs/waze/blinders/private-join-and-compute/BUILD:30:1: in srcs attribute of _generate_cc rule //:_private_join_and_compute_proto_grpc_codegen: '//:_private_join_and_compute_proto_only' does not have mandatory providers: 'proto'. Since this rule was created by the macro 'grpc_proto_library', the error might have been caused by the macro implementation
ERROR: Analysis of target '//:_private_join_and_compute_proto_grpc_codegen' failed; build aborted: Analysis of target '//:_private_join_and_compute_proto_grpc_codegen' failed; build aborted
INFO: Elapsed time: 0.315s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

**Comment by stevebriskin** [comment]
I ran into the same error with Bazel 1.10 but was able to compile with Bazel 0.28.1.

**Comment by jklein9d** [comment]
I downgraded to 0.28.1 of Bazel and was able to compile successfully using the alternate build.  Thank you Steve.

**Comment by tronch0** [comment]
I downgraded to 0.28.1 and used the alternate build too, thank you Steve.

**Comment by karnseth** [comment]
This should work on the latest version of Bazel, after commit 391f0934e537e4399365865f1421c6b8f757b966
